class DentalCompany:
    def __init__(self, company):
        self.__company = company
        self.__branches = []

    def get_name(self):
        return self.__company
    
    def add_branch(self, branch):
        self.__branches.append(branch)
    
    def get_branches(self):
        return self.__branches

class Branch:
    def __init__(self, address, phoneNumber, manager):
        self.__address = address
        self.__phone_number = phoneNumber
        self.__manager = manager
        self.__services = []
        self.__staff = []
        self.__patients = []

    def add_service(self, service):
        self.__services.append(service)

    def add_staff(self, staff):
        self.__staff.append(staff)

    def add_patient(self, patient):
        self.__patients.append(patient)

    def display_services(self):
        print("Services offered:")
        for service in self.__services:
            print(f"- {service.getName()} (${service.getCost()})")

    def display_staff(self):
        print("Staff members:")
        for staff in self.__staff:
            print(f"- {staff.getName()} ({staff.getRole()})")

    def display_patients(self):
        print("Patients:")
        for patient in self.__patients:
            print(f"- {patient.getName()}")

    def book_appointment(self, patient, service):
        print(f"{patient.getName()} has booked a {service.getName()} appointment on the branch {self.__address}")

    def checkout(self, patient):
        total_cost = 0
        print(f"Receipt for {patient.getName()}:")
        for service in patient.getServiceReceived():
            print(f"- {service.getName()} (${service.getCost()})")
            total_cost += service.getCost()
        vat = total_cost * 0.05
        total_cost += vat
        print(f"Total: ${total_cost} (including 5% VAT)")

class Service:
    def __init__(self, name, cost):
        self.__name = name
        self.__cost = cost

    def getName(self):
        return self.__name
    
    def getCost(self):
        return self.__cost
    
class Staff:
    def __init__(self, name, role):
        self.__name = name
        self.__role = role
    
    def getName(self):
        return self.__name
    
    def getRole(self):
        return self.__role

class Patient:
    def __init__(self, name):
        self.__name = name
        self.__services_received = []

    def receive_service(self, service):
        self.__services_received.append(service)

    def getName(self):
        return self.__name
    
    def getServiceReceived(self):
        return self.__services_received
    
class Manager(Staff):
    def __init__(self, name,role):
        super().__init__(name, role)
    
    def manage_staff(self, action, branch, memmber=None):
        if action == 'hire':
            if memmber is not None:
                branch.add_staff(memmber)
            else:
                print("No one was hired")

class Receptionist(Staff):
    def __init__(self, name, role):
        super().__init__(name, role)
    
    def book_appointment(self, patient, service, branch):
        print(f"{self.__name} has booked a {service.getName()} appointment for {patient.getName()} at {branch.__address}")
        branch.add_patient(patient)
    
    def getName(self):
        return self.__name
    
class Appointment:
    def __init__(self, patient, service, dateTime):
        self.__patient = patient
        self.__service = service
        self.__dateTime = dateTime

# Test case A: adding branches
company = DentalCompany('MagicDent')
branch1 = Branch("17 Sad Street", "658982", "Dr. Tom")
branch2 = Branch("32 Outside", "9842312", "Dr. Jerry")
company.add_branch(branch1)
company.add_branch(branch2)
# Test case B: adding services, staff, and patients to a branch
cleaning = Service("Cleaning", 50)
implants = Service("Implants", 1000)
receptionist = Staff("Sarah", "Receptionist")
dentist = Staff("Dr. Lee", "Dentist")
patient1 = Patient("Max")
patient2 = Patient("Mark")
branch1.add_service(cleaning)
branch1.add_service(implants)
branch1.add_staff(receptionist)
branch1.add_staff(dentist)
branch1.add_patient(patient1)
branch1.add_patient(patient2)

# Test case C: adding a patient appointment
print(f"Welcome to {company.get_name()}")
branch1.book_appointment(patient1, cleaning)
print(f"Invoice is generated by {receptionist.getName()}")
# Test case D: displaying receipt and final bill
patient1.receive_service(cleaning)
patient1.receive_service(implants)
branch1.checkout(patient1)
